### PR TITLE
Allow multiple request methods and export response headers

### LINKED ISSUE #21: Feature request: allow custom http methods and export headers
It would be great to have an ability to define:
* custom HTTP request method
* request body
* and export response headers

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #21

Based on the #20 

/cc @tyrannosaurus-becks @apparentlymart

### CODE REVIEW

**Comment by kayrus** [comment]
@apparentlymart kindly ping

**Comment by analytically** [comment]
Would be really handy to convert HCL to JSON via the /v1/jobs/parse Nomad endpoint!

**Comment by kayrus** [comment]
@tyrannosaurus-becks @apparentlymart any progress on reviewing this PR?

**Comment by jon-walton** [comment]
@kayrus I think this is awesome so far and will open up a number of workflow possibilities. I have a usecase question.

Let's say there is an API with the following routes

```text
GET /api/projects
POST /api/projects
DELETE api/projects/{id}
```

and I have a terraform resource

```hcl
resource "http" "my_project" {
  url = "https://api.example.com/api/projects"
  action {
    create {
      method = "POST"
      response_status_code = 201
    }

    delete {
      method = "DELETE"
      response_status_code = 204
    }
  }
}
```

How would I transform the URL for the DELETE method to be

`"https://api.example.com/api/projects/${http.my_project.id_from_create_response}"` ?

**Comment by kayrus** [comment]
@jon-walton just create two resources:

```
resource "http" "my_project" {
  url = "https://api.example.com/api/projects"
  action {
    create {
      method = "POST"
      response_status_code = 201
    }
  }
}

resource "http" "my_project_delete" {
  url = "${jsondecode(http.my_project.body).project_id}"
  action {
    delete {
      method = "DELETE"
      response_status_code = 204
    }
  }
}
```

**Comment by analytically** [comment]
Anything possible to speed up the merge of this PR?

**Comment by kayrus** [comment]
@tyrannosaurus-becks @apparentlymart kindly ping

**Comment by kayrus** [comment]
@apparentlymart kindly ping

**Comment by syntastical** [comment]
Is there anything holding this up?  I would be wonderful to have this.

**Comment by SiddhantAgarwal17** [comment]
Can we expedite this? We have problems using the http provider where the response is paginated. The response headers contains the number of pages and without access to response header we would just end up guessing the number of pages which doesn't help.

**Comment by kayrus** [comment]
@appilon could you please take a look on this PR? It's open for 6 months and I'm not the only one, who requests this feature.

**Comment by mbrancato** [comment]
@appilon have you reviewed this for merging?

**Comment by batesandy** [comment]
How close is it for this to be GA? I have a definite use case that would benefit from the multiple methods

**Comment by appilon** [comment]
Hello,

First of all thank you all for continued contributions to the provider ecosystem. My sincerest apologies for not addressing this pull request sooner. The HTTP provider is one of Hashicorp's utility providers, and typically serves very targeted and limited usecases. While there was discussion on [this PR](https://github.com/hashicorp/terraform-provider-http/pull/20) about how a resource lifecycle could map to the different HTTP verbs, after careful reflection, we would prefer not enhance this provider with those responsibilites, and keep it limited to a read only datasource.

We would accept a pull request that enhances the datasource (or perhaps create a new datasource) for performing HEAD requests. For full resource management via HTTP requests, we would recommend this [popular community provider](https://github.com/Mastercard/terraform-provider-restapi), or alternatively developing a custom provider.

This pull request also enhanced the datasource with response headers, this enhancement makes sense and we will prioritize getting [GH-31](https://github.com/hashicorp/terraform-provider-http/pull/31) merged and released.

**Comment by syntastical** [comment]
@appilon thats a load of bull. Hashicorps narrow view on how people need to use their technology is garbage. If your going to have an http provider it should be able to do a thing http related. Not some artificially restricted version. I’m done waiting for features. It’s time to move to another platform that doesn’t hinder people.

**Comment by sburton-sumo** [comment]
@appilon Could you expand on what you mean by

> after careful reflection, we would prefer not enhance this provider with those responsibilites, and keep it limited to a read only datasource.

What is the reasoning behind this preference?  It seems pretty reasonable to allow the http provider to allow more than one http verb.  For instance, this suggestion looks like what I would expect the http provider to be capable of https://github.com/hashicorp/terraform-provider-http/pull/20#issuecomment-507936261

**Comment by salrashid123** [comment]
added in a minimal varation for POST and mTLS endpoints here based on a recent fork of this repo  

* https://github.com/salrashid123/terraform-provider-http-full

**Pull request closed without merging**
