### PR TITLE
Allowed content-types controlled via Accept header.

### PR DESCRIPTION
**Pull request by mvanholsteijn**
This change will allow the user to control the accepted content types, by specifying the allowed content types in the Accept request header.

This avoids the problem where the response body is a string, but with a different content type than the hard coded ones (application/text, application/json and application/application/samlmetadata+xml).

Now, this will work:

```
data "http" "auth0-saml-metadata" {
  url = "http://httpbin.org/xml"
  request_headers  = {
      Accept = "application/xml"
  }
}

output "metadata" {
	value = "${data.http.auth0-saml-metadata.body}"
}
```

### CODE REVIEW

**Comment by mvanholsteijn** [comment]
@radeksimko I am looking forward to your comments.

**Comment by mvanholsteijn** [comment]
Can somebody tell me when this PR might be reviewed and possibly merged? 
@tombuildsstuff, @radeksimko

**Comment by niedbalski** [comment]
+1 to this MP, otherwise no other content-type is allowed.

**Comment by apparentlymart** [comment]
Hi @mvanholsteijn!

Sorry for the delay here; the Terraform team at HashiCorp is currently entirely focused on finishing the Core v0.12.0 release and so haven't been able to spend time with the various providers in a while. We plan to catch up on provider issues and PRs once the v0.12 release is concluded and stable.

With that said, although I can't do a full review here right now, I did take an initial look and I like the general idea here. One thing I'd suggest is to consider using [`mime.ParseMediaType`](https://golang.org/pkg/mime/#ParseMediaType) and string comparsion instead of the current regexp approach, if only because the `Accept` header is not defined to use regexp syntax and there may be unintended consequences such as panics if the result doesn't parse.

Although the original regexp-based approach was convenient when there was only a small number of hard-coded types, we know that the language for accepted mime types is much simpler:

* After successful return from `ParseMediaType`, we know that `mediatype` will be two strings separated by a slash; we can ignore and skip any string that fails parsing. (`ParseMediaType` can also take care of splitting of the `q`-weight, as we can see in [a simple example](https://play.golang.org/p/c3ARpPpEjjC).)
* For our matching rules, there are only two possibilities: exact string match, or wildcard `*`.
* We can therefore define a rule as being a `[2]string` value (array with two elements) where the strings can be either something literal like `"text"` or a wildcard represented by `"*"`.
* To match the rules, we already use `ParseMediaType` on the resulting `Content-Type` header, so we can also turn that result into a `[2]string` value for easy comparison.
* We can then iterate over the rules and check that the resulting content-type either exactly matches or the rule string is `"*"`. (`ParseMediaType` normalizes the type and subtype strings to lowercase, so we can just use a direct string comparison to match it.)

Our default set of rules would then be expressed like this:

```go
defaultAllowedTypes := [][2]string{
  {"text", "*"},
  {"application", "json"},
  {"application", "samlmetadata+xml"},
}
```

...and that can be combined with a value of the same type constructed from the `Accept` header to produce the full set of rules for a particular request.

Given an `Accept` header value like `application/atom+xml, application/rss+xml;q=0.9` the request-specific ruleset would be:

```go
[][2]string{
  {"application", "atom+xml"},
  {"application", "rss+xml"},
}
```

I think this approach will give more predictable and consistent results than continuing to use regular expressions, since it more closely follows the conventions of the relevant specifications.

**Comment by mvanholsteijn** [comment]
@apparentlymart I understand what you are saying. However I wrote this PR as small increment of the current implementation, which already used the regex comparison of the content type headers. 

I put in quite some effort to add it and add the unit tests so that it would pass, and I do not want to  to put in more effort to refactor the implementation. So I would appreciate it if you would merge it, or close the PR if you deem this implementation unacceptable.

**Comment by myrcutio** [comment]
> I think this approach will give more predictable and consistent results than continuing to use regular expressions, since it more closely follows the conventions of the relevant specifications.

@apparentlymart v0.12 was released some time ago and this MR solves a number off issues as-is.  If no one is going to offer up an alternative PR can we please get this in?

**Comment by invidian** [comment]
It would be nice to get that merged and released..

**Comment by TwoFifteen** [comment]
Hi @apparentlymart - Re: Allowed content-types controlled via Accept header - Just checking in here as this PR has been sitting for over a year. This also solves the issue for Terraform Cloud as I have not been able to find a solution to leverage a remote file when using TC in remote execution mode. As others have said, this moves the needle forward on the issue until the  this feature is refactored at a future date.

**Comment by mvanholsteijn** [comment]
Perhaps we can get this fix in before it is two years old?

**Comment by t0rr3sp3dr0** [comment]
The problem is still present on Terraform v0.12.24

**Comment by ivan-sukhomlyn** [comment]
Could somebody take a look at this PR, please?
I'm also looking for supporting the `application/xml` content type.

**Comment by acdha** [comment]
I just ran into this attempting to work around https://github.com/terraform-providers/terraform-provider-aws/issues/304 with a vendor's CloudFormation template which is JSON hosted in S3 with `Content-Type: binary/octet-stream`.

**Comment by archoversight** [comment]
I'd love to see this merged because Keycloak returns its SAML metadata as `application/xml;charset=UTF-8` which is still text, but is not treated as such.

**Comment by mvanholsteijn** [comment]
@archoversight I think that this PR will never be merged. When you  create a new PR according to @apparentlymart 
 redesign you may have a chance. https://github.com/hashicorp/terraform-provider-http/pull/16#issuecomment-477724762

**Comment by archoversight** [comment]
Sadly I don't have the necessary background in Go to be able to create a new pr that matches those design requirements. Instead I ended up pre-loading the file into our git repository and added manual steps in case the endpoint returned SAML metadata ever changes or stops functioning correctly so that it is updated across the repo.

**Comment by aicarmic** [comment]
Hello from the Providers team. @mvanholsteijn We appreciate both your suggestion and your patience on this PR, know that it has not been lost. As an update, our plan is to migrate this provider to using plugin-SDK 2.0.0 which is around the corner. Once upgraded, this will enable us to remove the restriction on `content-type` with the goal of allowing users to specify any content-type as a string in, along with a CLI warning that a non-standard type is being used. We should note that there are hard limits to state size, and also binary data content may not be handled properly but otherwise this should address https://github.com/hashicorp/terraform-provider-http/issues/15 by removing the limitation and offering flexibility.  

Please continue to follow https://github.com/hashicorp/terraform-provider-http/issues/15 for further updates and thanks again for your support and understanding.

**Comment by aicarmic** [comment]
@mvanholsteijn this has been resolved in https://github.com/hashicorp/terraform-provider-http/pull/50, and will be available in our upcoming 2.0.0 release.

**Comment by ivan-sukhomlyn** [comment]
@mvanholsteijn @aicarmic Thank you guys for your effort to have this functionality available :)

**Pull request closed without merging**
